version: '3.9'
services:
    some-zookeeper:
        image: confluentinc/cp-zookeeper:5.2.3
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        logging:
            driver: none
    some-kafka: 
        image: confluentinc/cp-kafka:4.1.2-2
        depends_on:
            - some-zookeeper
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
            KAFKA_ZOOKEEPER_CONNECT: some-zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: INTERNAL://some-kafka:29092,EXTERNAL://localhost:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
            KAFKA_SESSION_TIMEOUT_MS: 600000

volumes:
    mongodb-data:
        name: mongodb-data
        external: true
          
